openapi: 3.0.2

info: 
  title: 'Practica AOS gestión de vehículos subsistema_2'
  description: 'Práctica realizada por el grupo 4 realizando el subservicio de gestión de coches en el taller'
  version: '1.0'
  
  
tags:
  - name: 'vehículo'
    description: 'vehículo a gestionar'
    
    
paths:
  /vehiculo:
  
components: 
  schemas:
    vehiculo:
      description: 'objeto vehiculo a gestionar'
      title: 'vehiculo'
      type: object
      
      required:
      - VIN
      - matricula
      - marca
      - modelo
      - motor
      - clienteID
      - proposito
      
      properties:
        VIN:
          description: Identificador único de cada vehículo
          type: string
        matricula:
          description: Matrícula del vehículo
          type: string
        marca:
          description: Marca del vehículo (mercedes, porche, etc.)
          type : string
        modelo:
          description: Modelo de vehículo
          type: string
        año:
          description: Año de fabricación del vehiculo
          type: integer
          format: int32
        motor:
          description: Cilindrada del motor, CV del motor, tipo de motor.
          type: string
        clienteID:
          description: Identificador único del cliente propietario del vehículo
          type: string
        reparacionUltima:
          description: Año de la última reparación del vehículo
          type: integer
          nullable: true
          format: int32
        proposito:
          description: Propósito de la visita. Para reparar o revisar.
          type: string
          enum:
            - Reparar
            - Revisar
            - Reparar y Revisar
      example:
        vehiculo:
          VIN: MNCLSFE405W491230
          matricula: XEC4567YX
          marca: Ford
          modelo: Mustang
          año: 1987
          motor: V8, 500 CV, gasolina
          clienteID: qwer1234
          reparacionUltima: 2021
          proposito: Reparar y Revisar
          
    HTTP_Problem:
      type: object
      externalDocs:
        url: https://tools.ietf.org/html/rfc7807
      description: |
        Problem Details for HTTP APIs
        [https://tools.ietf.org/html/rfc7807](https://tools.ietf.org/html/rfc7807)
      properties:
        type:
          type: string
          format: uri
          description: A URI reference [RFC3986] that identifies the problem type
        title:
          type: string
          description: short human-readable summary of the problem type
        status:
          type: number
          description: HTTP status code
        detail:
          type: string
          description: human-readable explanation specific to this occurrence of the problem
        instance:
          type: string
          format: uri
          description: "A URI reference that identifies the specific
                    occurrence of the problem.  It may or may not yield further
                    information if dereferenced"
  
  responses:
    Response_200:
      description: '`OK`: el objeto ha sido modificado'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/'
          examples:
            response-http-200:
              $ref: '#/components/examples/response-http-200'

    Response_201:
      description: 'El recurso ha sido creado'
      Location: 
        $ref: '#/components/schemas/'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/'
          examples:
            response-http-201:
              $ref: '#/components/examples/response-http-201'  
  
    Response_400:
      description: '`Bad Request`: el recurso no se encuentra disponible'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/HTTP_Problem'
          examples:
            response-http-400:
              $ref: '#/components/examples/response-http-400'

    Response_401:
      description: '`UNAUTHORIZED`: no dispone de las credenciales válidas'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/HTTP_Problem'
          examples:
            response-http-401:
              $ref: '#/components/examples/response-http-401'
           
    Response_403:
      description: '`FORBIDDEN`: la petición no ha sido autorizada'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/HTTP_Problem'
          examples:
            response-http-403:
              $ref: '#/components/examples/response-http-403'
              
    Response_404:
      description: '`NOT FOUND`: el recurso no se encuentra disponible'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/HTTP_Problem'
          examples:
            response-http-404:
              $ref: '#/components/examples/response-http-404'

    Response_408:
      description: '`REQUEST_TIMEOUT`: se ha perdido la conexión con el recurso'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/HTTP_Problem'
          examples:
            response-http-408:
              $ref: '#/components/examples/response-http-408'      

    Response_500:
      description: 'Internal server error'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/HTTP_Problem'
          examples:
            response-http-500:
              $ref: '#/components/examples/response-http-500'  

  examples:
    response-http-200:
      value:
        type: https://httpstatuses.com/200
        title: OK
        status: 200
        detail: 'La petición realizada ha sido un éxito'
        instance: about:blank
        
    response-http-201:
      value:
        type: https://httpstatuses.com/200
        title: Resource Created
        status: 201
        detail: 'El recurso ha sido creado'
        instance: about:blank        
  
    response-http-400:
      value:
        type: https://httpstatuses.com/400
        title: Bad Request
        status: 400
        detail: 'La petición realizada es incorrecta'
        instance: about:blank

    response-http-401:
      value:
        type: https://httpstatuses.com/401
        title: UNAUTHORIZED
        status: 401
        detail: 'Las credenciales no son correctas'
        instance: about:blank

    response-http-403:
      value:
        type: https://httpstatuses.com/403
        title: FORBIDDEN
        status: 403
        detail: 'La petición es correcta pero no se autoriza'
        instance: about:blank
        
    response-http-404:
      value:
        type: https://httpstatuses.com/404
        title: NOT FOUND
        status: 404
        detail: 'El recurso con el vehículo solicitado no se encuentra disponible'
        instance: about:blank

    response-http-408:
      value:
        type: https://httpstatuses.com/408
        title: REQUEST_TIMEOUT
        status: 408
        detail: 'Se ha perdido la conexión con el servidor'
        instance: about:blank

    response-http-500:
      value:
        type: https://httpstatuses.com/500
        title: INTERNAL SERVER ERROR
        status: 500
        detail: 'Error en el servidor'
        instance: about:blank
    
        
        
        
        
        
        
           
            
  
  
